name: Build & Publish Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Setup Image Name
        run: echo "IMAGE_NAME=ghcr.io/katsurakii/reaction-role" >> $GITHUB_ENV

      - name: Docker Image Build (versioned + latest)
        run: |
          docker build -t $IMAGE_NAME:${{ github.run_number }} .
          docker tag $IMAGE_NAME:${{ github.run_number }} $IMAGE_NAME:latest

      - name: Docker Image Push (versioned)
        run: docker push $IMAGE_NAME:${{ github.run_number }} 
        
      - name: Docker Image Push (latest)
        run: docker push $IMAGE_NAME:latest
